name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup deps
      run: make deps

    - name: Make
      run: make all
    
    - uses: actions/upload-artifact@v2
      with:
        name: cworld.zip
        path: ./cworld.zip
